<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_loan</name>
   <tag></tag>
   <elementGuidId>f11526f8-df15-4af9-8c01-b6ebdd48bd30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='requestloan.htm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
