<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_findTransfer</name>
   <tag></tag>
   <elementGuidId>cc2b61b5-e896-45f2-af1c-b832b07da32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='findtrans.htm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
