<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_transfer</name>
   <tag></tag>
   <elementGuidId>de1141a1-e626-4d56-8c45-9e97dbb38b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='transfer.htm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
