<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_findByDate</name>
   <tag></tag>
   <elementGuidId>181a77ff-e987-41b3-92cc-a3a2343f5f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findByDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
