<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_findByDateRange</name>
   <tag></tag>
   <elementGuidId>5483ce8b-4b2b-4bf6-b6fc-88119708efdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findByDateRange</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
