<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_findByAmount</name>
   <tag></tag>
   <elementGuidId>76d747a4-df2f-4ed9-9c9e-961edc05a1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findByAmount</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
