<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_findById</name>
   <tag></tag>
   <elementGuidId>2b289133-ffa9-4409-b460-26a00ba95992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findById</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
