<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_account</name>
   <tag></tag>
   <elementGuidId>b3109cab-19ec-48b9-87a4-b3ce98f56e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountId</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
