<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_fromDate</name>
   <tag></tag>
   <elementGuidId>3ee900b9-86c0-4869-8f00-04408f2134c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
