<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_toDate</name>
   <tag></tag>
   <elementGuidId>80b84404-b67b-4a8d-92aa-6020508048f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
