<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_date</name>
   <tag></tag>
   <elementGuidId>fdd92c08-8ec0-4d56-bae7-8b65988d59dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transactionDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
